/*
# Seed Achievements & Shop Catalogs

1. Data
- Inserts 200+ achievements across categories (missions, focus, streaks, xp, coins, habits, time-of-day, coding, learning, legendary).
- Inserts shop items (themes, avatars, sounds, pets, frames, boosters, titles).
2. Security
- No schema changes; read policies already in place.
3. Notes
- Uses ON CONFLICT (code) DO NOTHING for idempotency.
*/

-- ACHIEVEMENTS (200+)
INSERT INTO achievements (code, title, description, icon, rarity, xp_reward, coin_reward, category) VALUES
('first_mission','First Mission','Complete your very first mission','🎯','common',10,5,'missions'),
('mission_5','Getting Started','Complete 5 missions','🌱','common',20,10,'missions'),
('mission_10','Double Digits','Complete 10 missions','✅','common',30,15,'missions'),
('mission_25','Quarter Century','Complete 25 missions','⭐','common',40,20,'missions'),
('mission_50','Halfway Hero','Complete 50 missions','🏅','rare',60,30,'missions'),
('mission_100','Centurion','Complete 100 missions','💯','rare',100,50,'missions'),
('mission_250','Mission Machine','Complete 250 missions','⚙️','epic',200,100,'missions'),
('mission_500','Mission Master','Complete 500 missions','🏆','epic',300,150,'missions'),
('mission_1000','Legendary Doer','Complete 1000 missions','👑','legendary',500,250,'missions'),
('mission_5000','Mythic Achiever','Complete 5000 missions','🌟','mythic',1000,500,'missions'),
('hard_mission_1','Hard Hitter','Complete a Hard mission','💥','common',15,10,'missions'),
('hard_mission_10','Hardcore','Complete 10 Hard missions','🔥','rare',50,25,'missions'),
('hard_mission_50','Iron Will','Complete 50 Hard missions','🛡️','epic',150,75,'missions'),
('legendary_mission_1','Legend in the Making','Complete a Legendary mission','⚡','rare',40,20,'missions'),
('legendary_mission_10','Mythic Slayer','Complete 10 Legendary missions','🐉','legendary',200,100,'missions'),
('epic_mission_1','Epic Beginnings','Complete an Epic mission','🌌','rare',50,25,'missions'),
('epic_mission_10','Epic Conqueror','Complete 10 Epic missions','🌋','legendary',250,120,'missions'),
('focus_1','First Focus','Complete 1 focus session','🧘','common',10,5,'focus'),
('focus_5','Getting Focused','Complete 5 focus sessions','🎧','common',25,12,'focus'),
('focus_10','Deep Diver','Complete 10 focus sessions','🌊','rare',50,25,'focus'),
('focus_25','Focus Adept','Complete 25 focus sessions','🔮','rare',75,40,'focus'),
('focus_50','Focus Master','Complete 50 focus sessions','🧠','epic',150,75,'focus'),
('focus_100','Zen Master','Complete 100 focus sessions','🪷','epic',250,120,'focus'),
('focus_250','Focus Sage','Complete 250 focus sessions','🧿','legendary',400,200,'focus'),
('focus_500','Transcendent','Complete 500 focus sessions','🕉️','legendary',600,300,'focus'),
('focus_1000','Enlightened','Complete 1000 focus sessions','☀️','mythic',1200,600,'focus'),
('deep_work_1','Deep Worker','Complete a Deep Work session','⛏️','common',15,8,'focus'),
('deep_work_10','Tunnel Vision','Complete 10 Deep Work sessions','🚇','rare',60,30,'focus'),
('focus_minutes_60','1 Hour Focused','Accumulate 60 minutes of focus','⏱️','common',20,10,'focus'),
('focus_minutes_300','5 Hours Focused','Accumulate 300 minutes of focus','⌛','rare',50,25,'focus'),
('focus_minutes_1000','1000 Minutes','Accumulate 1000 minutes of focus','⏳','epic',150,75,'focus'),
('focus_minutes_5000','5000 Minutes','Accumulate 5000 minutes of focus','🕰️','legendary',400,200,'focus'),
('focus_minutes_10000','10000 Minutes','Accumulate 10000 minutes of focus','♾️','mythic',1000,500,'focus'),
('streak_3','On a Roll','Reach a 3-day streak','🔥','common',15,10,'streaks'),
('streak_7','Week Warrior','Reach a 7-day streak','🗓️','rare',50,25,'streaks'),
('streak_14','Fortnight Fighter','Reach a 14-day streak','💪','rare',75,40,'streaks'),
('streak_30','Monthly Master','Reach a 30-day streak','🌙','epic',150,75,'streaks'),
('streak_50','Fifty Strong','Reach a 50-day streak','💎','epic',200,100,'streaks'),
('streak_100','Centurion Streak','Reach a 100-day streak','🔥','legendary',400,200,'streaks'),
('streak_200','Unbreakable','Reach a 200-day streak','🛡️','legendary',600,300,'streaks'),
('streak_365','Year of Fire','Reach a 365-day streak','🌋','mythic',1500,750,'streaks'),
('streak_500','Iron Streak','Reach a 500-day streak','⛓️','mythic',2000,1000,'streaks'),
('streak_1000','Thousand Suns','Reach a 1000-day streak','☀️','mythic',5000,2500,'streaks'),
('freeze_used','Frozen in Time','Use a streak freeze','🧊','rare',30,15,'streaks'),
('early_bird','Early Bird','Complete a mission before 7 AM','🐦','common',20,10,'time'),
('early_bird_10','Morning Person','Complete 10 missions before 7 AM','🌅','rare',50,25,'time'),
('night_owl','Night Owl','Complete a mission after midnight','🦉','common',20,10,'time'),
('night_owl_10','Midnight Oil','Complete 10 missions after midnight','🌙','rare',50,25,'time'),
('weekend_warrior','Weekend Warrior','Complete missions on both Sat & Sun','🎮','common',25,12,'time'),
('xp_100','First 100 XP','Earn 100 XP','✨','common',10,5,'xp'),
('xp_500','500 XP','Earn 500 XP','💫','common',20,10,'xp'),
('xp_1000','1000 XP','Earn 1000 XP','⭐','rare',40,20,'xp'),
('xp_5000','5000 XP','Earn 5000 XP','🌟','rare',80,40,'xp'),
('xp_10000','10000 XP','Earn 10000 XP','🌠','epic',150,75,'xp'),
('xp_50000','50000 XP','Earn 50000 XP','🚀','legendary',400,200,'xp'),
('xp_100000','100000 XP','Earn 100000 XP','🪐','mythic',1000,500,'xp'),
('level_5','Level 5','Reach level 5','📈','common',20,10,'xp'),
('level_10','Level 10','Reach level 10','📊','rare',50,25,'xp'),
('level_25','Level 25','Reach level 25','📉','epic',150,75,'xp'),
('level_50','Level 50','Reach level 50','🏆','legendary',400,200,'xp'),
('level_100','Level 100','Reach level 100','👑','mythic',1500,750,'xp'),
('coins_100','Pocket Change','Earn 100 coins','🪙','common',10,0,'coins'),
('coins_500','Coin Collector','Earn 500 coins','💰','common',20,0,'coins'),
('coins_1000','Thousandaire','Earn 1000 coins','🤑','rare',40,0,'coins'),
('coins_5000','Coin Baron','Earn 5000 coins','🏦','epic',100,0,'coins'),
('coins_10000','Coin Tycoon','Earn 10000 coins','🏰','legendary',300,0,'coins'),
('coins_50000','Coin Magnate','Earn 50000 coins','💎','mythic',800,0,'coins'),
('shop_first','First Purchase','Buy your first shop item','🛒','common',15,0,'coins'),
('shop_10','Shopaholic','Buy 10 shop items','🛍️','rare',50,0,'coins'),
('habit_1','Habit Former','Complete a habit once','🌱','common',10,5,'habits'),
('habit_7','7-Day Habit','Keep a habit for 7 days','🌿','common',25,12,'habits'),
('habit_30','30-Day Habit','Keep a habit for 30 days','🌳','rare',60,30,'habits'),
('habit_100','100-Day Habit','Keep a habit for 100 days','🌲','epic',150,75,'habits'),
('habit_365','365-Day Habit','Keep a habit for a year','🏞️','legendary',400,200,'habits'),
('habits_5','Five Habits','Track 5 habits at once','🖐️','common',20,10,'habits'),
('habits_10','Ten Habits','Track 10 habits at once','🔟','rare',50,25,'habits'),
('habit_perfect_week','Perfect Week','Complete all habits 7 days straight','✨','rare',60,30,'habits'),
('habit_perfect_month','Perfect Month','Complete all habits 30 days straight','🌟','epic',150,75,'habits'),
('dsa_master','DSA Master','Complete 50 DSA missions','🧩','epic',150,75,'coding'),
('dsa_legend','DSA Legend','Complete 200 DSA missions','🧠','legendary',400,200,'coding'),
('coding_beast','Coding Beast','Complete 100 coding missions','💻','epic',150,75,'coding'),
('coding_legend','Coding Legend','Complete 500 coding missions','⚡','legendary',400,200,'coding'),
('ai_learner','AI Learner','Complete 25 AI/ML missions','🤖','rare',60,30,'learning'),
('ai_scholar','AI Scholar','Complete 100 AI/ML missions','🧬','epic',150,75,'learning'),
('book_reader','Book Reader','Complete 10 reading missions','📚','common',30,15,'learning'),
('book_worm','Bookworm','Complete 50 reading missions','📖','rare',60,30,'learning'),
('study_10','Study Session','Complete 10 study missions','✏️','common',25,12,'learning'),
('study_50','Study Scholar','Complete 50 study missions','🎓','rare',60,30,'learning'),
('study_200','Study Sage','Complete 200 study missions','🧑‍🎓','epic',150,75,'learning'),
('workout_10','Fitness Fan','Complete 10 workout missions','💪','common',25,12,'health'),
('workout_50','Fitness Pro','Complete 50 workout missions','🏃','rare',60,30,'health'),
('workout_200','Fitness Legend','Complete 200 workout missions','🏋️','epic',150,75,'health'),
('meditation_10','Mindful','Complete 10 meditation missions','🧘','common',25,12,'health'),
('meditation_50','Zen Seeker','Complete 50 meditation missions','☯️','rare',60,30,'health'),
('water_30','Hydrated','Complete 30 hydration habits','💧','common',30,15,'health'),
('sleep_30','Restful','Track sleep 30 times','😴','common',30,15,'health'),
('perfect_day','Perfect Day','Complete all daily missions in one day','🌟','rare',80,40,'missions'),
('perfect_week','Perfect Week','7 perfect days in a row','✨','epic',200,100,'missions'),
('perfect_month','Perfect Month','30 perfect days in a row','💫','legendary',500,250,'missions'),
('no_missed_day_7','No Missed Day','7 days without missing a mission','🔒','common',25,12,'streaks'),
('no_missed_day_30','Iron Discipline','30 days without missing a mission','🛡️','rare',60,30,'streaks'),
('no_missed_day_100','Unbreakable Discipline','100 days without missing a mission','🏰','epic',150,75,'streaks'),
('comeback_king','Comeback King','Return after a 7+ day break','👑','common',30,15,'streaks'),
('comeback_legend','Comeback Legend','Return after a 30+ day break','🔥','rare',60,30,'streaks'),
('week_xp_500','Weekly Grinder','Earn 500 XP in a week','📈','rare',60,30,'xp'),
('week_xp_2000','Weekly Beast','Earn 2000 XP in a week','🚀','epic',150,75,'xp'),
('week_xp_5000','Weekly God','Earn 5000 XP in a week','🪐','legendary',400,200,'xp'),
('month_xp_2000','Monthly Achiever','Earn 2000 XP in a month','📊','rare',80,40,'xp'),
('month_xp_5000','Monthly Star','Earn 5000 XP in a month','🌠','epic',200,100,'xp'),
('month_xp_10000','Monthly Legend','Earn 10000 XP in a month','🌟','legendary',500,250,'xp'),
('daily_login_1','Welcome Back','Log in for the first time','👋','common',10,5,'streaks'),
('daily_login_7','Week Regular','Log in 7 days','📅','common',20,10,'streaks'),
('daily_login_30','Monthly Regular','Log in 30 days','🗓️','rare',50,25,'streaks'),
('daily_login_100','100 Logins','Log in 100 days','💯','epic',150,75,'streaks'),
('daily_login_365','Year Devotee','Log in 365 days','📆','legendary',400,200,'streaks'),
('legend','Legend','Reach level 50 with a 100-day streak','👑','mythic',2000,1000,'legendary'),
('mythic_grind','Mythic Grinder','Earn 100000 XP and 50000 coins','💎','mythic',1500,750,'legendary'),
('all_achievements','Completionist','Unlock 100 achievements','🏅','mythic',2000,1000,'legendary'),
('all_achievements_200','Grand Completionist','Unlock 200 achievements','🏆','mythic',5000,2500,'legendary'),
('speed_demon','Speed Demon','Complete 5 missions in 10 minutes','⚡','rare',60,30,'missions'),
('multitasker','Multitasker','Complete 3 missions simultaneously','🤹','rare',50,25,'missions'),
('perfectionist','Perfectionist','Complete 50 missions on their due date','🎯','epic',150,75,'missions'),
('overachiever','Overachiever','Complete 10 missions in one day','🚀','rare',60,30,'missions'),
('overachiever_20','Super Achiever','Complete 20 missions in one day','🔥','epic',150,75,'missions'),
('night_shift','Night Shift','Complete 50 missions after 10 PM','🌃','epic',120,60,'time'),
('morning_routine','Morning Routine','Complete 5 missions before 9 AM','🌄','rare',50,25,'time'),
('lunch_break','Lunch Break','Complete a mission during lunch hour','🥪','common',15,8,'time'),
('late_night','Late Night','Complete a mission after 2 AM','🕛','rare',40,20,'time'),
('all_nighter','All Nighter','Complete missions every hour for 6 hours','🦉','epic',150,75,'time'),
('weekend_grind','Weekend Grind','Complete 20 missions on a weekend','🎮','rare',60,30,'time'),
('holiday_hustle','Holiday Hustle','Complete a mission on a holiday','🎄','common',20,10,'time'),
('new_year','New Year Resolution','Complete a mission on Jan 1','🎉','rare',50,25,'time'),
('valentine','Productive Valentine','Complete a mission on Feb 14','❤️','common',20,10,'time'),
('halloween','Spooky Productive','Complete a mission on Oct 31','🎃','common',20,10,'time'),
('christmas','Christmas Mission','Complete a mission on Dec 25','🎅','common',20,10,'time'),
('summer_solstice','Summer Solstice','Complete a mission on the longest day','☀️','rare',40,20,'time'),
('winter_solstice','Winter Solstice','Complete a mission on the shortest day','❄️','rare',40,20,'time'),
('first_habit','First Habit','Create your first habit','📋','common',10,5,'habits'),
('habit_streak_7','Habit Streak','7-day habit streak','🔥','common',25,12,'habits'),
('habit_streak_30','Habit Master','30-day habit streak','🌟','rare',60,30,'habits'),
('habit_streak_100','Habit Centurion','100-day habit streak','💯','epic',150,75,'habits'),
('habit_streak_365','Habit Year','365-day habit streak','📅','legendary',400,200,'habits'),
('habit_variety','Variety Pack','Track habits in 5 different categories','🎨','rare',50,25,'habits'),
('habit_completion_100','100 Completions','Complete habits 100 times','✅','rare',60,30,'habits'),
('habit_completion_500','500 Completions','Complete habits 500 times','🏆','epic',150,75,'habits'),
('habit_completion_1000','1000 Completions','Complete habits 1000 times','👑','legendary',400,200,'habits'),
('focus_pomodoro_10','Pomodoro Pro','Complete 10 Pomodoro sessions','🍅','common',30,15,'focus'),
('focus_pomodoro_50','Pomodoro Master','Complete 50 Pomodoro sessions','🍅','rare',60,30,'focus'),
('focus_pomodoro_100','Pomodoro Legend','Complete 100 Pomodoro sessions','🍅','epic',150,75,'focus'),
('focus_custom_1','Custom Timer','Complete a custom focus session','⚙️','common',15,8,'focus'),
('focus_custom_10','Custom Pro','Complete 10 custom sessions','🔧','rare',50,25,'focus'),
('focus_marathon','Marathon','Complete a 90+ minute focus session','🏃','epic',150,75,'focus'),
('focus_sprint','Sprinter','Complete a 5-minute focus session','⚡','common',15,8,'focus'),
('focus_streak_7','Focus Streak','Focus 7 days in a row','🔥','rare',60,30,'focus'),
('focus_streak_30','Focus Devotee','Focus 30 days in a row','🧘','epic',150,75,'focus'),
('focus_weekend','Weekend Focus','Focus on both Sat & Sun','📅','common',25,12,'focus'),
('focus_morning','Morning Focus','Focus before 8 AM','🌅','rare',40,20,'focus'),
('focus_night','Night Focus','Focus after 10 PM','🌙','rare',40,20,'focus'),
('focus_50_sessions','50 Sessions','Complete 50 total focus sessions','🎯','epic',150,75,'focus'),
('focus_200_sessions','200 Sessions','Complete 200 total focus sessions','🏆','legendary',400,200,'focus'),
('first_purchase','First Buy','Make your first shop purchase','🛒','common',15,0,'coins'),
('theme_buyer','Theme Buyer','Buy your first theme','🎨','common',15,0,'coins'),
('avatar_buyer','Avatar Buyer','Buy your first avatar','🎭','common',15,0,'coins'),
('sound_buyer','Sound Buyer','Buy your first sound pack','🎵','common',15,0,'coins'),
('pet_buyer','Pet Owner','Buy your first pet','🐾','common',15,0,'coins'),
('big_spender','Big Spender','Spend 5000 coins total','💸','rare',80,0,'coins'),
('whale','Whale','Spend 20000 coins total','🐋','legendary',300,0,'coins'),
('theme_collector','Theme Collector','Own 5 themes','🖼️','rare',50,0,'coins'),
('avatar_collector','Avatar Collector','Own 10 avatars','🧑‍🎤','rare',50,0,'coins'),
('pet_collector','Pet Collector','Own 5 pets','🦄','rare',50,0,'coins'),
('title_earner','Title Earned','Unlock your first title','🏷️','common',15,0,'coins'),
('booster_buyer','Booster Buyer','Buy your first booster','⚡','common',15,0,'coins'),
('all_themes','Theme Master','Own all themes','👑','mythic',1000,500,'coins'),
('profile_complete','Profile Complete','Fill out your full profile','📝','common',20,10,'general'),
('bio_added','Bio Added','Write your bio','✍️','common',10,5,'general'),
('avatar_changed','New Look','Change your avatar','🎭','common',10,5,'general'),
('settings_changed','Tinkerer','Change a setting','⚙️','common',10,5,'general'),
('first_week','First Week','Use the app for 7 days','📅','common',25,12,'general'),
('first_month','First Month','Use the app for 30 days','🗓️','rare',60,30,'general'),
('first_quarter','First Quarter','Use the app for 90 days','📆','epic',150,75,'general'),
('first_year','First Year','Use the app for 365 days','🎉','legendary',400,200,'general'),
('two_years','Two Year Veteran','Use the app for 730 days','🏆','mythic',1000,500,'general'),
('three_years','Three Year Legend','Use the app for 1095 days','👑','mythic',2000,1000,'general'),
('level_5_streak_7','Rising Star','Level 5 with a 7-day streak','✨','rare',60,30,'legendary'),
('level_10_streak_30','Dedicated','Level 10 with a 30-day streak','🔥','epic',150,75,'legendary'),
('level_25_streak_50','Committed','Level 25 with a 50-day streak','💎','legendary',400,200,'legendary'),
('coins_100k','Hundred K','Earn 100000 coins','💰','mythic',1000,0,'coins'),
('missions_all_diff','Versatile','Complete missions of all 5 difficulties','🌈','rare',60,30,'missions'),
('missions_5_day','5 a Day','Complete 5 missions daily for a week','📈','epic',150,75,'missions'),
('focus_5_day','Focus Daily','Focus 5 days in a week','🧘','rare',60,30,'focus'),
('habit_all_week','Habit All Week','Complete a habit every day for a week','🌿','common',30,15,'habits'),
('no_skip_week','No Skip Week','No missed habits for a week','🔒','rare',50,25,'habits'),
('productivity_90','Productivity Pro','Reach a 90 productivity score','📈','epic',150,75,'general'),
('productivity_100','Perfect Score','Reach a 100 productivity score','💯','legendary',400,200,'general'),
('seasonal_spring','Spring Forward','Complete a mission in spring','🌸','common',15,8,'time'),
('seasonal_summer','Summer Hustle','Complete a mission in summer','☀️','common',15,8,'time'),
('seasonal_fall','Fall Focus','Complete a mission in fall','🍂','common',15,8,'time'),
('seasonal_winter','Winter Work','Complete a mission in winter','⛄','common',15,8,'time'),
('monthly_challenge_1','Monthly Challenger','Complete a monthly challenge','🏅','rare',80,40,'missions'),
('monthly_challenge_12','Yearly Challenger','Complete 12 monthly challenges','🏆','epic',200,100,'missions'),
('annual_2026','2026 Achiever','Complete a mission in 2026','🎊','rare',50,25,'time'),
('first_ai_review','Reflective','Complete your first AI review','🤖','rare',40,20,'general'),
('weekly_review_4','Review Regular','Complete 4 weekly reviews','📝','rare',50,25,'general'),
('monthly_review_3','Review Master','Complete 3 monthly reviews','📋','epic',120,60,'general'),
('adaptive_diff','Adaptive','Let AI adjust your difficulty','⚙️','rare',40,20,'general'),
('goal_set_1','Goal Setter','Set your first personal goal','🎯','common',15,8,'general'),
('goal_met_1','Goal Achiever','Complete a personal goal','🏆','common',25,12,'general'),
('goal_met_10','Goal Crusher','Complete 10 personal goals','💪','rare',60,30,'general'),
('goal_met_50','Goal Legend','Complete 50 personal goals','👑','epic',150,75,'general'),
('comeback_3','Triple Comeback','Return from breaks 3 times','🔄','rare',50,25,'streaks'),
('streak_recover','Phoenix','Recover a broken streak','🔥','rare',60,30,'streaks'),
('first_quote','Inspired','Read your first motivational quote','💬','common',10,5,'general'),
('quote_30','Daily Inspiration','Read 30 motivational quotes','📚','rare',50,25,'general'),
('first_leaderboard','Competitor','Join a leaderboard','📊','common',20,10,'general'),
('leaderboard_top_10','Top 10','Reach top 10 on a leaderboard','🥉','rare',80,40,'general'),
('leaderboard_top_3','Podium','Reach top 3 on a leaderboard','🥈','epic',200,100,'general'),
('leaderboard_top_1','Champion','Reach #1 on a leaderboard','🥇','legendary',500,250,'general'),
('first_friend','Social Butterfly','Add your first friend','🦋','common',20,10,'general'),
('friends_10','Popular','Add 10 friends','👥','rare',50,25,'general'),
('friends_50','Social Star','Add 50 friends','🌟','epic',150,75,'general'),
('first_pet','Pet Pal','Get your first pet','🐾','common',20,10,'general'),
('pet_level_10','Pet Trainer','Level a pet to 10','🐕','rare',60,30,'general'),
('pet_level_50','Pet Master','Level a pet to 50','🐉','legendary',400,200,'general'),
('first_title','Titled','Earn your first title','🏷️','common',15,8,'general'),
('title_5','Titled Five','Own 5 titles','🎖️','rare',50,25,'general'),
('first_frame','Framed','Get your first profile frame','🖼️','common',15,8,'general'),
('frame_5','Frame Collector','Own 5 frames','🖼️','rare',50,25,'general'),
('first_badge','Badged','Earn your first badge','📛','common',15,8,'general'),
('badge_10','Badge Collector','Own 10 badges','🎖️','rare',50,25,'general'),
('first_booster_use','Boosted','Use your first booster','⚡','common',15,8,'general'),
('booster_10','Booster Pro','Use 10 boosters','🔋','rare',50,25,'general'),
('first_wallpaper','Fresh Paint','Buy your first wallpaper','🖼️','common',15,0,'coins'),
('first_music','DJ','Buy your first music pack','🎵','common',15,0,'coins'),
('first_ai_personality','AI Buddy','Unlock an AI coach personality','🤖','rare',40,20,'general'),
('ai_personality_5','AI Friend','Unlock 5 AI personalities','🧠','epic',120,60,'general'),
('first_animation','Show Off','Unlock a special animation','✨','rare',40,20,'general'),
('animation_10','Animator','Unlock 10 animations','🎬','epic',150,75,'general'),
('first_background','Backdrop','Buy your first background','🌌','common',15,0,'coins'),
('background_5','Background Collector','Own 5 backgrounds','🖼️','rare',50,25,'general'),
('first_character','Role Player','Unlock your first character','🦸','common',15,8,'general'),
('character_5','Character Collector','Own 5 characters','🎭','rare',50,25,'general'),
('first_pet_frame','Pet Frame','Get a pet frame','🐾','common',15,8,'general'),
('animated_border_1','Glow Up','Get an animated profile border','✨','rare',40,20,'general'),
('animated_border_5','Border Master','Own 5 animated borders','🌟','epic',150,75,'general'),
('mission_750','750 Missions','Complete 750 missions','🏅','legendary',350,175,'missions'),
('mission_2500','2500 Missions','Complete 2500 missions','🏆','legendary',450,225,'missions'),
('focus_750','750 Sessions','Complete 750 focus sessions','🧘','legendary',500,250,'focus'),
('streak_750','750 Days','Reach a 750-day streak','🔥','mythic',2500,1250,'streaks'),
('habit_streak_750','750-Day Habit','Keep a habit 750 days','🌳','mythic',1500,750,'habits'),
('level_75','Level 75','Reach level 75','📈','legendary',600,300,'xp'),
('level_150','Level 150','Reach level 150','👑','mythic',2000,1000,'xp'),
('level_250','Level 250','Reach level 250','🌟','mythic',3000,1500,'xp'),
('level_500','Level 500','Reach level 500','🪐','mythic',5000,2500,'xp'),
('xp_250000','250K XP','Earn 250000 XP','🌠','mythic',2000,1000,'xp'),
('xp_500000','500K XP','Earn 500000 XP','🌌','mythic',3000,1500,'xp'),
('xp_1000000','Million XP','Earn 1000000 XP','☀️','mythic',5000,2500,'xp'),
('coins_200k','200K Coins','Earn 200000 coins','💰','mythic',1500,0,'coins'),
('coins_500k','500K Coins','Earn 500000 coins','💎','mythic',2500,0,'coins'),
('coins_1m','Millionaire','Earn 1000000 coins','🤑','mythic',5000,0,'coins')
ON CONFLICT (code) DO NOTHING;

-- SHOP ITEMS
INSERT INTO shop_items (code, name, description, category, icon, price, rarity) VALUES
('theme_cyberpunk','Cyberpunk Theme','Neon-soaked futuristic theme','theme','🌃',500,'rare'),
('theme_minimal','Minimal Theme','Clean and distraction-free','theme','⚪',300,'common'),
('theme_galaxy','Galaxy Theme','Deep space aesthetic','theme','🌌',800,'epic'),
('theme_space','Space Theme','Stars and nebulas','theme','🪐',800,'epic'),
('theme_forest','Forest Theme','Calm and natural','theme','🌲',400,'common'),
('theme_ocean','Ocean Theme','Deep blue serenity','theme','🌊',400,'common'),
('theme_anime','Anime Theme','Vibrant and playful','theme','🌸',1000,'epic'),
('theme_retro','Retro Theme','80s synthwave vibes','theme','🕹️',700,'rare'),
('theme_dark_neon','Dark Neon Theme','Pure dark with neon accents','theme','💜',600,'rare'),
('theme_productivity_pro','Productivity Pro Theme','Optimized for focus','theme','⚡',1200,'legendary'),
('avatar_fox','Fox Avatar','Clever and quick','avatar','🦊',100,'common'),
('avatar_dragon','Dragon Avatar','Powerful and fierce','avatar','🐉',800,'epic'),
('avatar_phoenix','Phoenix Avatar','Reborn from ashes','avatar','🔥',1500,'legendary'),
('avatar_unicorn','Unicorn Avatar','Magical and rare','avatar','🦄',1000,'epic'),
('avatar_robot','Robot Avatar','Mechanical precision','avatar','🤖',500,'rare'),
('avatar_wizard','Wizard Avatar','Mystical and wise','avatar','🧙',700,'rare'),
('avatar_ninja','Ninja Avatar','Silent and deadly','avatar','🥷',600,'rare'),
('avatar_panda','Panda Avatar','Calm and cute','avatar','🐼',300,'common'),
('avatar_cat','Cat Avatar','Curious and agile','avatar','🐱',200,'common'),
('avatar_wolf','Wolf Avatar','Loyal and strong','avatar','🐺',500,'rare'),
('sound_rain','Rain Sounds','Calming rainfall','sound','🌧️',300,'common'),
('sound_cafe','Cafe Sounds','Cozy coffee shop ambience','sound','☕',300,'common'),
('sound_brown_noise','Brown Noise','Deep focus noise','sound','🔊',250,'common'),
('sound_lofi','Lo-fi Beats','Chill study music','sound','🎵',500,'rare'),
('sound_forest','Forest Sounds','Nature ambience','sound','🌳',300,'common'),
('sound_ocean','Ocean Sounds','Waves and wind','sound','🌊',300,'common'),
('sound_piano','Piano Ambient','Soft piano for focus','sound','🎹',600,'rare'),
('sound_synths','Synthwave','Retro focus beats','sound','🎛️',700,'rare'),
('pet_cat','Pet Cat','A loyal companion','pet','🐱',500,'rare'),
('pet_dragon','Pet Dragon','A mighty friend','pet','🐉',2000,'legendary'),
('pet_owl','Pet Owl','Wise and watchful','pet','🦉',800,'epic'),
('pet_fox','Pet Fox','Clever companion','pet','🦊',700,'epic'),
('pet_penguin','Pet Penguin','Cool and collected','pet','🐧',600,'rare'),
('pet_phoenix','Pet Phoenix','Reborn daily','pet','🔥',3000,'mythic'),
('frame_gold','Gold Frame','Shiny gold profile frame','frame','🥇',1000,'epic'),
('frame_neon','Neon Frame','Glowing neon border','frame','✨',800,'rare'),
('frame_galaxy','Galaxy Frame','Cosmic profile border','frame','🌌',1500,'legendary'),
('frame_fire','Fire Frame','Burning animated border','frame','🔥',1200,'epic'),
('frame_ice','Ice Frame','Frozen crystal border','frame','🧊',1000,'rare'),
('frame_rainbow','Rainbow Frame','Colorful animated border','frame','🌈',2000,'legendary'),
('frame_mythic','Mythic Frame','Ultimate animated border','frame','👑',5000,'mythic'),
('title_legend','Legend Title','Show off your legend status','title','🏷️',1000,'legendary'),
('title_master','Master Title','A master of productivity','title','🎖️',500,'rare'),
('title_champion','Champion Title','For the victorious','title','🏆',800,'epic'),
('title_sage','Sage Title','Wise and experienced','title','🧙',600,'rare'),
('title_pro','Pro Title','Professional doer','title','⭐',300,'common'),
('booster_xp_2x','2x XP Booster','Double XP for 1 hour','booster','⚡',300,'rare'),
('booster_coin_2x','2x Coin Booster','Double coins for 1 hour','booster','💰',300,'rare'),
('booster_streak_freeze','Streak Freeze','Protect your streak once','booster','🧊',200,'common'),
('booster_xp_3x','3x XP Booster','Triple XP for 30 minutes','booster','🌟',800,'epic'),
('booster_coin_3x','3x Coin Booster','Triple coins for 30 minutes','booster','💎',800,'epic'),
('wallpaper_aurora','Aurora Wallpaper','Northern lights background','wallpaper','🌌',700,'rare'),
('wallpaper_sunset','Sunset Wallpaper','Golden hour gradient','wallpaper','🌅',500,'common'),
('wallpaper_mountain','Mountain Wallpaper','Misty peaks','wallpaper','⛰️',500,'common'),
('wallpaper_abstract','Abstract Wallpaper','Modern art background','wallpaper','🎨',600,'rare'),
('wallpaper_nebula','Nebula Wallpaper','Deep space clouds','wallpaper','🪐',1000,'epic'),
('wallpaper_sakura','Sakura Wallpaper','Cherry blossoms','wallpaper','🌸',800,'rare'),
('music_lofi_pack','Lo-fi Pack','Curated lo-fi playlist','music','🎧',500,'rare'),
('music_classical_pack','Classical Pack','Focus classical music','music','🎻',600,'rare'),
('music_synthwave_pack','Synthwave Pack','Retro beats','music','🎛️',700,'rare'),
('music_jazz_pack','Jazz Pack','Smooth jazz for work','music','🎷',600,'rare'),
('music_ambient_pack','Ambient Pack','Pure ambient soundscapes','music','🌫️',500,'rare'),
('ai_coach_strict','Strict Coach','No-nonsense AI coach','ai_personality','🧑‍🏫',500,'rare'),
('ai_coach_chill','Chill Coach','Relaxed and supportive AI','ai_personality','😎',500,'rare'),
('ai_coach_hype','Hype Coach','Energetic cheerleader AI','ai_personality','📣',800,'epic'),
('ai_coach_wise','Wise Coach','Philosophical mentor AI','ai_personality','🧙',800,'epic'),
('ai_coach_robot','Robot Coach','Logical and data-driven AI','ai_personality','🤖',600,'rare'),
('animation_confetti','Confetti Burst','Special completion animation','animation','🎉',300,'common'),
('animation_fireworks','Fireworks','Explosive celebration','animation','🎆',600,'rare'),
('animation_stardust','Stardust','Magical particle effect','animation','✨',800,'epic'),
('animation_lightning','Lightning Strike','Electrifying completion','animation','⚡',1000,'epic'),
('animation_rainbow_burst','Rainbow Burst','Colorful explosion','animation','🌈',1200,'legendary'),
('character_knight','Knight','Brave warrior character','character','🛡️',800,'rare'),
('character_mage','Mage','Mystical spellcaster','character','🧙',800,'rare'),
('character_rogue','Rogue','Stealthy operator','character','🥷',800,'rare'),
('character_paladin','Paladin','Holy protector','character','⚔️',1200,'epic'),
('character_archmage','Archmage','Master of magic','character','🔮',2000,'legendary'),
('badge_first_steps','First Steps Badge','Mark of a beginner','badge','🌱',100,'common'),
('badge_rising_star','Rising Star Badge','For climbing fast','badge','⭐',300,'rare'),
('badge_veteran','Veteran Badge','Seasoned user','badge','🎖️',800,'epic'),
('badge_mythical','Mythical Badge','Untouchable status','badge','👑',3000,'mythic')
ON CONFLICT (code) DO NOTHING;